ALTER TABLE OcorrenciasLog
DROP FOREIGN KEY FK_OcorrenciasLog_ErrosLog;

-- Log
DROP TABLE IF EXISTS ErrosLog;

CREATE TABLE IF NOT EXISTS ErrosLog (
    ID INT AUTO_INCREMENT NOT NULL,
    Aplicacao VARCHAR(255) NULL,
    Nome VARCHAR(255) NULL,
    Data DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    Tipo VARCHAR(255) NULL,
    Mensagem VARCHAR(255) NULL,
    Arquivo VARCHAR(255) NULL,
    Stack TEXT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS OcorrenciasLog;

CREATE TABLE IF NOT EXISTS OcorrenciasLog (
    ID INT AUTO_INCREMENT NOT NULL,
    IDErro INT NOT NULL,
    Aplicacao VARCHAR(255) NULL,
    Data DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    CONSTRAINT FK_OcorrenciasLog_ErrosLog FOREIGN KEY (IDErro) REFERENCES ErrosLog(ID)
);
ALTER TABLE Cargos
DROP FOREIGN KEY FK_Cargos_Usuarios;
-- USUARIOS
DROP TABLE IF EXISTS Usuarios;

CREATE TABLE IF NOT EXISTS Usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Login VARCHAR(30) NOT NULL,
    Senha VARCHAR(200) NOT NULL,
    IDCargo INT NOT NULL,
    Email VARCHAR(200) DEFAULT NULL,
    Ativo BIT NOT NULL DEFAULT b'1',
    DataCriado DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    DataAlterado DATETIME(6) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
    UsuarioCriado VARCHAR(255) DEFAULT 'SISTEMA',
    UsuarioAlterado VARCHAR(255) DEFAULT NULL
);


DROP TABLE IF EXISTS Cargos;

CREATE TABLE IF NOT EXISTS Cargos (
    ID INT AUTO_INCREMENT NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Ativo BOOLEAN NOT NULL DEFAULT TRUE,
    DataCriado DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    DataAlterado DATETIME(6) NULL,
    IDUsuarioCriado INT NOT NULL DEFAULT 0,
    IDUsuarioAlterado INT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

ALTER TABLE Usuarios
ADD CONSTRAINT FK_Usuarios_Cargos
FOREIGN KEY (IDCargo) REFERENCES Cargos(ID);

-- Modulos
DROP TABLE IF EXISTS Modulos;

CREATE TABLE IF NOT EXISTS Modulos (
    ID INT AUTO_INCREMENT NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Ativo BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (ID)
);


-- Paginas
DROP TABLE IF EXISTS Paginas;

CREATE TABLE IF NOT EXISTS Paginas (
    ID INT AUTO_INCREMENT NOT NULL,
    IDModulo INT NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Url VARCHAR(100) NULL,
    Icone VARCHAR(100) NOT NULL,
    Ordem INT NOT NULL,
    Ativo BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (ID),
    CONSTRAINT FK_Paginas_Modulos FOREIGN KEY (IDModulo) REFERENCES Modulos(ID)
);
-- Permissoes
DROP TABLE IF EXISTS Permissoes;

CREATE TABLE IF NOT EXISTS Permissoes (
    ID INT AUTO_INCREMENT NOT NULL,
    IDCargo INT NOT NULL,
    IDModulo INT NOT NULL,
    IDPagina INT NOT NULL,
    Criar BOOLEAN NOT NULL DEFAULT FALSE,
    Revisar BOOLEAN NOT NULL DEFAULT FALSE,
    Editar BOOLEAN NOT NULL DEFAULT FALSE,
    Deletar BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID),
    CONSTRAINT FK_Permissoes_Modulos FOREIGN KEY (IDModulo) REFERENCES Modulos(ID),
    CONSTRAINT FK_Permissoes_Paginas FOREIGN KEY (IDPagina) REFERENCES Paginas(ID)
);


ALTER TABLE Permissoes
ADD CONSTRAINT FK_Permissoes_Paginas FOREIGN KEY (IDPagina) REFERENCES Paginas(ID);

ALTER TABLE Paginas
ADD CONSTRAINT FK_Paginas_Modulos FOREIGN KEY (IDModulo) REFERENCES Modulos(ID);

