ALTER TABLE OcorrenciasLog
DROP FOREIGN KEY FK_OcorrenciasLog_ErrosLog;

-- Log
DROP TABLE IF EXISTS ErrosLog;

CREATE TABLE IF NOT EXISTS ErrosLog (
    ID INT AUTO_INCREMENT NOT NULL,
    Aplicacao VARCHAR(255) NULL,
    Nome VARCHAR(255) NULL,
    Data DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    Tipo VARCHAR(255) NULL,
    Mensagem VARCHAR(255) NULL,
    Arquivo VARCHAR(255) NULL,
    Stack TEXT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS OcorrenciasLog;

CREATE TABLE IF NOT EXISTS OcorrenciasLog (
    ID INT AUTO_INCREMENT NOT NULL,
    IDErro INT NOT NULL,
    Aplicacao VARCHAR(255) NULL,
    Data DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    CONSTRAINT FK_OcorrenciasLog_ErrosLog FOREIGN KEY (IDErro) REFERENCES ErrosLog(ID)
);
ALTER TABLE Cargos
DROP FOREIGN KEY FK_Cargos_Usuarios;
-- USUARIOS
DROP TABLE IF EXISTS Usuarios;

CREATE TABLE IF NOT EXISTS Usuarios (
    ID INT AUTO_INCREMENT NOT NULL,
    Nome VARCHAR(150) NOT NULL,
    Login VARCHAR(30) NOT NULL,
    Senha VARCHAR(200) NOT NULL,
    IDCargo INT NOT NULL,
    Email VARCHAR(200) NULL,
    Ativo BOOLEAN NOT NULL DEFAULT TRUE,
    DataCriado DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    DataAlterado DATETIME(6) NULL,
    IDUsuarioCriado INT NOT NULL DEFAULT 0,
    IDUsuarioAlterado INT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Cargos;

CREATE TABLE IF NOT EXISTS Cargos (
    ID INT AUTO_INCREMENT NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Ativo BOOLEAN NOT NULL DEFAULT TRUE,
    DataCriado DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    DataAlterado DATETIME(6) NULL,
    IDUsuarioCriado INT NOT NULL DEFAULT 0,
    IDUsuarioAlterado INT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

ALTER TABLE Usuarios
ADD CONSTRAINT FK_Usuarios_Cargos
FOREIGN KEY (IDCargo) REFERENCES Cargos(ID);
